import { ProficiencyLevel } from "@prisma/client";
import { v } from "./vocab";
import type { DomainSpec } from "./types";

/** 动漫、美食、旅行、商务、音乐、运动、科技、历史 */
export const DOMAINS_A: DomainSpec[] = [
  {
    slug: "anime",
    nameZh: "动漫",
    nameJa: "アニメ",
    category: "entertainment",
    icon: "🎌",
    sortOrder: 1,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "动漫角色介绍",
        description: "学习介绍动漫角色的基础词汇与短句",
        objectives: ["说出常见角色相关词汇", "用简单句介绍喜欢的角色"],
        vocab: [
          v("角色", "jué sè", "キャラクター"),
          v("可爱", "kě ài", "かわいい"),
          v("主角", "zhǔ jué", "主人公"),
          v("名字", "míng zi", "名前"),
        ],
        dialogue: [
          { speaker: "A", text: "你最喜欢哪个角色？", pinyin: "nǐ zuì xǐ huan nǎ ge jué sè?", meaning: "一番好きなキャラはどれ？" },
          { speaker: "B", text: "我喜欢主角，他很可爱。", pinyin: "wǒ xǐ huan zhǔ jué, tā hěn kě ài", meaning: "主人公が好き。とてもかわいい。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "动漫台词模仿",
        description: "模仿动漫中常见的鼓励与感叹表达",
        objectives: ["掌握常见口语感叹", "模仿简短台词"],
        vocab: [
          v("厉害", "lì hai", "すごい"),
          v("加油", "jiā yóu", "頑張って"),
          v("太棒了", "tài bàng le", "最高だ"),
          v("真的吗", "zhēn de ma", "本当？"),
          v("感动", "gǎn dòng", "感動した"),
        ],
        dialogue: [
          { speaker: "A", text: "这一集太棒了！", pinyin: "zhè yī jí tài bàng le!", meaning: "この回は最高！" },
          { speaker: "B", text: "真的吗？我也很感动。", pinyin: "zhēn de ma? wǒ yě hěn gǎn dòng", meaning: "本当？私も感動した。" },
          { speaker: "A", text: "加油，主角一定能赢！", pinyin: "jiā yóu, zhǔ jué yī dìng néng yíng!", meaning: "頑張って、主人公はきっと勝てる！" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "观看感想表达",
        description: "用更自然的句子分享看动漫的感受",
        objectives: ["描述剧情感受", "表达推荐意愿"],
        vocab: [
          v("剧情", "jù qíng", "ストーリー・あらすじ"),
          v("精彩", "jīng cǎi", "見どころがある"),
          v("推荐", "tuī jiàn", "おすすめする"),
          v("画风", "huà fēng", "作画スタイル"),
          v("结局", "jié jú", "結末"),
        ],
        dialogue: [
          { speaker: "A", text: "这部动漫的剧情很精彩。", pinyin: "zhè bù dòng màn de jù qíng hěn jīng cǎi", meaning: "このアニメのストーリーはとても見どころがある。" },
          { speaker: "B", text: "我也喜欢它的画风。", pinyin: "wǒ yě xǐ huan tā de huà fēng", meaning: "作画スタイルも好きだよ。" },
          { speaker: "A", text: "强烈推荐你看结局那一集。", pinyin: "qiáng liè tuī jiàn nǐ kàn jié jú nà yī jí", meaning: "結末の回は強くおすすめするよ。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "动漫剧情讨论",
        description: "连贯讨论角色发展与故事走向",
        objectives: ["分析角色成长", "讨论剧情转折"],
        vocab: [
          v("伏笔", "fú bǐ", "伏線"),
          v("反转", "fǎn zhuǎn", "どんでん返し"),
          v("成长", "chéng zhǎng", "成長"),
          v("配音", "pèi yīn", "吹き替え・声優"),
          v("原作", "yuán zuò", "原作"),
        ],
        dialogue: [
          { speaker: "A", text: "前面的伏笔在最后有了反转。", pinyin: "qián miàn de fú bǐ zài zuì hòu yǒu le fǎn zhuǎn", meaning: "前半の伏線が最後にどんでん返しになった。" },
          { speaker: "B", text: "主角的成长线比原作更细腻。", pinyin: "zhǔ jué de chéng zhǎng xiàn bǐ yuán zuò gèng xì nì", meaning: "主人公の成長描写は原作より繊細だ。" },
          { speaker: "A", text: "配音演员的表现也很出色。", pinyin: "pèi yīn yǎn yuán de biǎo xiàn yě hěn chū sè", meaning: "声優の演技も素晴らしい。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "动漫文化深谈",
        description: "接近真实口语的动漫文化话题交流",
        objectives: ["讨论亚文化现象", "表达个人审美观点"],
        vocab: [
          v("二次元", "èr cì yuán", "二次元文化"),
          v("同人", "tóng rén", "同人作品"),
          v("周边", "zhōu biān", "グッズ・関連商品"),
          v("情怀", "qíng huái", "思い入れ・ノスタルジー"),
          v("入坑", "rù kēng", "ハマる・沼に落ちる"),
          v("神作", "shén zuò", "神作品"),
        ],
        dialogue: [
          { speaker: "A", text: "我入坑二次元就是因为这部神作。", pinyin: "wǒ rù kēng èr cì yuán jiù shì yīn wèi zhè bù shén zuò", meaning: "二次元にハマったのはこの神作品のおかげだ。" },
          { speaker: "B", text: "同人文化也承载了很多情怀。", pinyin: "tóng rén wén huà yě chéng zǎi le hěn duō qíng huái", meaning: "同人文化にも多くの思い入れが込められている。" },
          { speaker: "A", text: "展会上的周边每次都能带给我惊喜。", pinyin: "zhǎn huì shàng de zhōu biān měi cì dōu néng dài gěi wǒ jīng xǐ", meaning: "イベントのグッズは毎回驚きをくれる。" },
        ],
      },
    },
  },
  {
    slug: "food",
    nameZh: "美食",
    nameJa: "グルメ",
    category: "lifestyle",
    icon: "🍜",
    sortOrder: 2,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "餐厅基础点餐",
        description: "在餐厅点餐的最基本用语",
        objectives: ["说出菜单与点餐词汇", "完成简单点餐"],
        vocab: [
          v("菜单", "cài dān", "メニュー"),
          v("要", "yào", "〜をください（欲しい）"),
          v("水", "shuǐ", "お水"),
          v("米饭", "mǐ fàn", "ご飯"),
        ],
        dialogue: [
          { speaker: "服务员", text: "请看菜单。", pinyin: "qǐng kàn cài dān", meaning: "メニューをどうぞ。" },
          { speaker: "客人", text: "我要一碗米饭。", pinyin: "wǒ yào yī wǎn mǐ fàn", meaning: "ご飯を一つください。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "口味表达",
        description: "表达咸淡、辣度与口味偏好",
        objectives: ["描述味道", "提出口味要求"],
        vocab: [
          v("好吃", "hǎo chī", "おいしい"),
          v("辣", "là", "辛い"),
          v("清淡", "qīng dàn", "あっさりした"),
          v("咸", "xián", "しょっぱい"),
          v("甜", "tián", "甘い"),
        ],
        dialogue: [
          { speaker: "A", text: "这道菜很好吃，但有点辣。", pinyin: "zhè dào cài hěn hǎo chī, dàn yǒu diǎn là", meaning: "この料理はおいしいけど、少し辛い。" },
          { speaker: "B", text: "可以做得清淡一点吗？", pinyin: "kě yǐ zuò de qīng dàn yī diǎn ma?", meaning: "もう少しあっさりにできますか？" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "餐厅评价",
        description: "评价餐厅环境、服务与菜品",
        objectives: ["综合描述用餐体验", "给出评价意见"],
        vocab: [
          v("环境", "huán jìng", "雰囲気・環境"),
          v("服务", "fú wù", "サービス"),
          v("新鲜", "xīn xiān", "新鮮"),
          v("分量", "fèn liang", "量"),
          v("买单", "mǎi dān", "お会計"),
        ],
        dialogue: [
          { speaker: "A", text: "这家餐厅环境很好，服务也快。", pinyin: "zhè jiā cān tīng huán jìng hěn hǎo, fú wù yě kuài", meaning: "この店は雰囲気もよく、サービスも速い。" },
          { speaker: "B", text: "食材很新鲜，分量也足。", pinyin: "shí cái hěn xīn xiān, fèn liang yě zú", meaning: "食材は新鮮で、量も十分だ。" },
          { speaker: "A", text: "买单吧，下次再来。", pinyin: "mǎi dān ba, xià cì zài lái", meaning: "お会計しよう。また来よう。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "美食推荐",
        description: "向他人推荐餐厅与地方特色美食",
        objectives: ["介绍地方菜", "说明推荐理由"],
        vocab: [
          v("特色", "tè sè", "名物・特色"),
          v("招牌菜", "zhāo pái cài", "看板メニュー"),
          v("地道", "dì dao", "本格的・地元らしい"),
          v("排队", "pái duì", "並ぶ"),
          v("值得", "zhí de", "〜する価値がある"),
        ],
        dialogue: [
          { speaker: "A", text: "这家店的招牌菜很值得排队。", pinyin: "zhè jiā diàn de zhāo pái cài hěn zhí de pái duì", meaning: "この店の看板メニューは並ぶ価値がある。" },
          { speaker: "B", text: "有什么地道特色吗？", pinyin: "yǒu shén me dì dao tè sè ma?", meaning: "本格的な名物はある？" },
          { speaker: "A", text: "我推荐他们的地方特色火锅。", pinyin: "wǒ tuī jiàn tā men de dì fāng tè sè huǒ guō", meaning: "地元の特色火鍋をおすすめする。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "饮食文化讨论",
        description: "深入讨论中华饮食文化与传统",
        objectives: ["比较饮食文化", "表达饮食哲学"],
        vocab: [
          v("火候", "huǒ hou", "火加減"),
          v("风味", "fēng wèi", "風味"),
          v("传承", "chuán chéng", "受け継ぐ"),
          v("讲究", "jiǎng jiu", "こだわる"),
          v("宴席", "yàn xí", "宴会"),
          v("品味", "pǐn wèi", "味わい・センス"),
        ],
        dialogue: [
          { speaker: "A", text: "中国菜很讲究火候和风味。", pinyin: "zhōng guó cài hěn jiǎng jiu huǒ hou hé fēng wèi", meaning: "中国料理は火加減と風味にこだわる。" },
          { speaker: "B", text: "传统宴席也承载着文化传承。", pinyin: "chuán tǒng yàn xí yě chéng zǎi zhe wén huà chuán chéng", meaning: "伝統的な宴会にも文化の継承がある。" },
          { speaker: "A", text: "品味美食也是品味生活。", pinyin: "pǐn wèi měi shí yě shì pǐn wèi shēng huó", meaning: "美食を味わうことは人生を味わうことだ。" },
        ],
      },
    },
  },
  {
    slug: "travel",
    nameZh: "旅行",
    nameJa: "旅行",
    category: "lifestyle",
    icon: "✈️",
    sortOrder: 3,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "简单问路",
        description: "旅行中最基本的问路用语",
        objectives: ["询问地点方向", "理解简单指路"],
        vocab: [
          v("哪里", "nǎ lǐ", "どこ"),
          v("怎么走", "zěn me zǒu", "どう行けばいいですか"),
          v("左边", "zuǒ bian", "左"),
          v("右边", "yòu bian", "右"),
        ],
        dialogue: [
          { speaker: "游客", text: "地铁站怎么走？", pinyin: "dì tiě zhàn zěn me zǒu?", meaning: "地下鉄駅へはどう行けばいいですか？" },
          { speaker: "路人", text: "往左边走。", pinyin: "wǎng zuǒ bian zǒu", meaning: "左に進んでください。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "订票出行",
        description: "购买车票与确认行程信息",
        objectives: ["购买交通票", "确认时间车次"],
        vocab: [
          v("火车票", "huǒ chē piào", "切符・乗車券"),
          v("几点", "jǐ diǎn", "何時"),
          v("出发", "chū fā", "出発"),
          v("到达", "dào dá", "到着"),
          v("站台", "zhàn tái", "ホーム・番線"),
        ],
        dialogue: [
          { speaker: "A", text: "我想买一张火车票。", pinyin: "wǒ xiǎng mǎi yī zhāng huǒ chē piào", meaning: "切符を一枚買いたいです。" },
          { speaker: "B", text: "火车几点出发？", pinyin: "huǒ chē jǐ diǎn chū fā?", meaning: "電車は何時に出発しますか？" },
          { speaker: "A", text: "请在三号站台等车。", pinyin: "qǐng zài sān hào zhàn tái děng chē", meaning: "3番ホームでお待ちください。" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "酒店入住",
        description: "办理入住、询问设施与服务",
        objectives: ["完成入住登记", "询问酒店服务"],
        vocab: [
          v("预订", "yù dìng", "予約"),
          v("入住", "rù zhù", "チェックイン"),
          v("护照", "hù zhào", "パスポート"),
          v("早餐", "zǎo cān", "朝食"),
          v("退房", "tuì fáng", "チェックアウト"),
        ],
        dialogue: [
          { speaker: "客人", text: "我有预订，想办理入住。", pinyin: "wǒ yǒu yù dìng, xiǎng bàn lǐ rù zhù", meaning: "予約があります、チェックインしたいです。" },
          { speaker: "前台", text: "请出示护照。", pinyin: "qǐng chū shì hù zhào", meaning: "パスポートをお見せください。" },
          { speaker: "前台", text: "早餐七点开始，退房时间是中午十二点。", pinyin: "zǎo cān qī diǎn kāi shǐ, tuì fáng shí jiān shì zhōng wǔ shí èr diǎn", meaning: "朝食は7時から、チェックアウトは正午12時です。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "旅行计划",
        description: "讨论行程安排与景点选择",
        objectives: ["描述行程", "协商旅行计划"],
        vocab: [
          v("行程", "xíng chéng", "旅程・スケジュール"),
          v("景点", "jǐng diǎn", "観光スポット"),
          v("自由行", "zì yóu xíng", "自由旅行"),
          v("预算", "yù suàn", "予算"),
          v("攻略", "gōng lüè", "旅行ガイド・攻略情報"),
        ],
        dialogue: [
          { speaker: "A", text: "我们这次自由行预算有限。", pinyin: "wǒ men zhè cì zì yóu xíng yù suàn yǒu xiàn", meaning: "今回の自由旅行は予算が限られている。" },
          { speaker: "B", text: "先看攻略，再安排行程。", pinyin: "xiān kàn gōng lüè, zài ān pái xíng chéng", meaning: "まず攻略を見てから旅程を組もう。" },
          { speaker: "A", text: "第一天去历史景点怎么样？", pinyin: "dì yī tiān qù lì shǐ jǐng diǎn zěn me yàng?", meaning: "初日は歴史的スポットに行くのはどう？" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "深度旅行交流",
        description: "分享旅行见闻与文化体验",
        objectives: ["描述文化差异", "讲述旅行故事"],
        vocab: [
          v("见闻", "jiàn wén", "見聞"),
          v("体验", "tǐ yàn", "体験"),
          v("风土人情", "fēng tǔ rén qíng", "風土と人情"),
          v("背包客", "bēi bāo kè", "バックパッカー"),
          v("驻足", "zhù zú", "立ち止まる"),
          v("足迹", "zú jì", "足跡"),
        ],
        dialogue: [
          { speaker: "A", text: "旅行不仅是看景点，更是体验风土人情。", pinyin: "lǚ xíng bù jǐn shì kàn jǐng diǎn, gèng shì tǐ yàn fēng tǔ rén qíng", meaning: "旅行は観光だけでなく、風土と人情を体験することだ。" },
          { speaker: "B", text: "我在小城驻足三天，收获很多见闻。", pinyin: "wǒ zài xiǎo chéng zhù zú sān tiān, shōu huò hěn duō jiàn wén", meaning: "小さな町に3日滞在し、多くの見聞を得た。" },
          { speaker: "A", text: "背包客的足迹往往最动人。", pinyin: "bēi bāo kè de zú jì wǎng wǎng zuì dòng rén", meaning: "バックパッカーの足跡はいつも心に残る。" },
        ],
      },
    },
  },
  {
    slug: "business",
    nameZh: "商务",
    nameJa: "ビジネス",
    category: "career",
    icon: "💼",
    sortOrder: 4,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "商务问候",
        description: "职场初次见面的礼貌问候",
        objectives: ["掌握商务问候语", "礼貌自我介绍"],
        vocab: [
          v("您好", "nín hǎo", "こんにちは（丁寧）"),
          v("公司", "gōng sī", "会社"),
          v("经理", "jīng lǐ", "マネージャー"),
          v("请多关照", "qǐng duō guān zhào", "よろしくお願いします"),
        ],
        dialogue: [
          { speaker: "A", text: "您好，我是ABC公司的。", pinyin: "nín hǎo, wǒ shì ABC gōng sī de", meaning: "こんにちは、ABC会社の者です。" },
          { speaker: "B", text: "请多关照。", pinyin: "qǐng duō guān zhào", meaning: "よろしくお願いします。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "商务自我介绍",
        description: "介绍职位、部门与工作内容",
        objectives: ["介绍职位", "说明负责业务"],
        vocab: [
          v("部门", "bù mén", "部署"),
          v("负责", "fù zé", "担当する"),
          v("销售", "xiāo shòu", "営業"),
          v("市场", "shì chǎng", "市場"),
          v("合作", "hé zuò", "協力・提携"),
        ],
        dialogue: [
          { speaker: "A", text: "我在市场部门负责销售。", pinyin: "wǒ zài shì chǎng bù mén fù zé xiāo shòu", meaning: "市場部で営業を担当しています。" },
          { speaker: "B", text: "希望今后能合作。", pinyin: "xī wàng jīn hòu néng hé zuò", meaning: "今後ご協力できれば幸いです。" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "会议发言",
        description: "在会议中陈述观点与回应",
        objectives: ["发表意见", "同意或补充观点"],
        vocab: [
          v("会议", "huì yì", "会議"),
          v("提案", "tí àn", "提案"),
          v("同意", "tóng yì", "同意する"),
          v("补充", "bǔ chōng", "補足する"),
          v("数据", "shù jù", "データ"),
        ],
        dialogue: [
          { speaker: "A", text: "我先说明一下提案的背景。", pinyin: "wǒ xiān shuō míng yī xià tí àn de bèi jǐng", meaning: "まず提案の背景を説明します。" },
          { speaker: "B", text: "我同意，但需要补充一些数据。", pinyin: "wǒ tóng yì, dàn xū yào bǔ chōng yī xiē shù jù", meaning: "同意しますが、データの補足が必要です。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "邮件与汇报",
        description: "商务邮件与进度汇报常用表达",
        objectives: ["汇报进度", "礼貌催促与确认"],
        vocab: [
          v("汇报", "huì bào", "報告"),
          v("附件", "fù jiàn", "添付ファイル"),
          v("截止", "jié zhǐ", "締め切り"),
          v("确认", "què rèn", "確認する"),
          v("安排", "ān pái", "手配・段取り"),
        ],
        dialogue: [
          { speaker: "A", text: "请查收邮件附件中的报表。", pinyin: "qǐng chá shōu yóu jiàn fù jiàn zhōng de bào biǎo", meaning: "メールの添付の報告書をご確認ください。" },
          { speaker: "B", text: "截止日期前我会确认并安排。", pinyin: "jié zhǐ rì qī qián wǒ huì què rèn bìng ān pái", meaning: "締め切り前に確認して段取りします。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "合作谈判",
        description: "商务合作与条件协商的高级表达",
        objectives: ["协商条款", "表达合作诚意"],
        vocab: [
          v("条款", "tiáo kuǎn", "条項"),
          v("双赢", "shuāng yíng", "ウィンウィン"),
          v("诚意", "chéng yì", "誠意"),
          v("让步", "ràng bù", "譲歩"),
          v("签约", "qiān yuē", "契約締結"),
          v("长期", "cháng qī", "長期的"),
        ],
        dialogue: [
          { speaker: "A", text: "我们追求双赢，希望长期合作。", pinyin: "wǒ men zhuī qiú shuāng yíng, xī wàng cháng qī hé zuò", meaning: "ウィンウィンを目指し、長期的な提携を望みます。" },
          { speaker: "B", text: "可以在条款上各退一步，体现诚意。", pinyin: "kě yǐ zài tiáo kuǎn shàng gè tuì yī bù, tǐ xiàn chéng yì", meaning: "条項でお互い譲歩し、誠意を示しましょう。" },
          { speaker: "A", text: "若达成一致，下周可以签约。", pinyin: "ruò dá chéng yī zhì, xià zhōu kě yǐ qiān yuē", meaning: "合意できれば来週契約できます。" },
        ],
      },
    },
  },
  {
    slug: "music",
    nameZh: "音乐",
    nameJa: "音楽",
    category: "entertainment",
    icon: "🎵",
    sortOrder: 5,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "喜欢的音乐",
        description: "表达喜欢什么音乐",
        objectives: ["说出音乐类型", "表达喜好"],
        vocab: [
          v("音乐", "yīn yuè", "音楽"),
          v("喜欢", "xǐ huan", "好き"),
          v("流行", "liú xíng", "ポップ・流行"),
          v("好听", "hǎo tīng", "聴きやすい・いい曲"),
        ],
        dialogue: [
          { speaker: "A", text: "你喜欢什么音乐？", pinyin: "nǐ xǐ huan shén me yīn yuè?", meaning: "どんな音楽が好き？" },
          { speaker: "B", text: "我喜欢流行音乐。", pinyin: "wǒ xǐ huan liú xíng yīn yuè", meaning: "ポップスが好きです。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "歌手介绍",
        description: "介绍喜欢的歌手与歌曲",
        objectives: ["介绍歌手", "推荐歌曲"],
        vocab: [
          v("歌手", "gē shǒu", "歌手"),
          v("歌词", "gē cí", "歌詞"),
          v("旋律", "xuán lǜ", "メロディー"),
          v("专辑", "zhuān jí", "アルバム"),
          v("单曲", "dān qǔ", "シングル"),
        ],
        dialogue: [
          { speaker: "A", text: "你听过这位歌手的新专辑吗？", pinyin: "nǐ tīng guò zhè wèi gē shǒu de xīn zhuān jí ma?", meaning: "この歌手の新アルバム聞いた？" },
          { speaker: "B", text: "旋律很好听，歌词也很感人。", pinyin: "xuán lǜ hěn hǎo tīng, gē cí yě hěn gǎn rén", meaning: "メロディーがよくて、歌詞も感動的だ。" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "演唱会体验",
        description: "描述演唱会现场体验",
        objectives: ["描述现场氛围", "分享观演感受"],
        vocab: [
          v("演唱会", "yǎn chàng huì", "ライブ・コンサート"),
          v("现场", "xiàn chǎng", "ライブ会場"),
          v("气氛", "qì fēn", "雰囲気"),
          v("合唱", "hé chàng", "合唱"),
          v("Encore", "ān kòu", "アンコール"),
        ],
        dialogue: [
          { speaker: "A", text: "昨晚的演唱会气氛太棒了。", pinyin: "zuó wǎn de yǎn chàng huì qì fēn tài bàng le", meaning: "昨夜のライブの雰囲気は最高だった。" },
          { speaker: "B", text: "全场一起合唱，让我很感动。", pinyin: "quán chǎng yī qǐ hé chàng, ràng wǒ hěn gǎn dòng", meaning: "会場全体で合唱して感動した。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "音乐评论",
        description: "评价音乐风格与作品质量",
        objectives: ["分析音乐风格", "评价作品"],
        vocab: [
          v("风格", "fēng gé", "スタイル"),
          v("编曲", "biān qǔ", "編曲"),
          v("突破", "tū pò", "突破"),
          v("经典", "jīng diǎn", "クラシック・名作"),
          v("现场版", "xiàn chǎng bǎn", "ライブ版"),
        ],
        dialogue: [
          { speaker: "A", text: "这张专辑在风格上有很大突破。", pinyin: "zhè zhāng zhuān jí zài fēng gé shàng yǒu hěn dà tū pò", meaning: "このアルバムはスタイルで大きな突破がある。" },
          { speaker: "B", text: "现场版比录音室版更有感染力。", pinyin: "xiàn chǎng bǎn bǐ lù yīn shì bǎn gèng yǒu gǎn rǎn lì", meaning: "ライブ版はスタジオ版より感染力がある。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "音乐文化深谈",
        description: "讨论音乐文化与审美取向",
        objectives: ["比较音乐文化", "表达审美观点"],
        vocab: [
          v("民谣", "mín yáo", "フォーク"),
          v("独立音乐", "dú lì yīn yuè", "インディーズ"),
          v("审美", "shěn měi", "美的センス"),
          v("共鸣", "gòng míng", "共感"),
          v("跨界", "kuà jiè", "クロスオーバー"),
          v("底蕴", "dǐ yùn", "深み・蓄積"),
        ],
        dialogue: [
          { speaker: "A", text: "独立音乐往往更能引发共鸣。", pinyin: "dú lì yīn yuè wǎng wǎng gèng néng yǐn fā gòng míng", meaning: "インディーズは共感を呼びやすい。" },
          { speaker: "B", text: "民谣的底蕴来自生活体验。", pinyin: "mín yáo de dǐ yùn lái zì shēng huó tǐ yàn", meaning: "フォークの深みは生活体験から来る。" },
          { speaker: "A", text: "跨界合作也丰富了审美可能。", pinyin: "kuà jiè hé zuò yě fēng fù le shěn měi kě néng", meaning: "クロスオーバーは美的可能性を広げる。" },
        ],
      },
    },
  },
  {
    slug: "sports",
    nameZh: "运动",
    nameJa: "スポーツ",
    category: "lifestyle",
    icon: "⚽",
    sortOrder: 6,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "运动爱好",
        description: "谈论喜欢的运动项目",
        objectives: ["说出运动名称", "表达喜好"],
        vocab: [
          v("运动", "yùn dòng", "スポーツ"),
          v("足球", "zú qiú", "サッカー"),
          v("跑步", "pǎo bù", "ランニング"),
          v("打球", "dǎ qiú", "球技をする"),
        ],
        dialogue: [
          { speaker: "A", text: "你喜欢什么运动？", pinyin: "nǐ xǐ huan shén me yùn dòng?", meaning: "どんなスポーツが好き？" },
          { speaker: "B", text: "我喜欢跑步和打球。", pinyin: "wǒ xǐ huan pǎo bù hé dǎ qiú", meaning: "ランニングと球技が好きです。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "观看比赛",
        description: "谈论比赛结果与精彩瞬间",
        objectives: ["描述比赛", "表达加油助威"],
        vocab: [
          v("比赛", "bǐ sài", "試合"),
          v("赢", "yíng", "勝つ"),
          v("输", "shū", "負ける"),
          v("加油", "jiā yóu", "頑張れ"),
          v("精彩", "jīng cǎi", "精彩な"),
        ],
        dialogue: [
          { speaker: "A", text: "昨晚足球比赛很精彩。", pinyin: "zuó wǎn zú qiú bǐ sài hěn jīng cǎi", meaning: "昨夜のサッカーの試合は精彩だった。" },
          { speaker: "B", text: "我们队赢了，加油！", pinyin: "wǒ men duì yíng le, jiā yóu!", meaning: "うちのチームが勝った、頑張れ！" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "训练打卡",
        description: "描述训练计划与身体状态",
        objectives: ["说明训练内容", "描述身体感受"],
        vocab: [
          v("训练", "xùn liàn", "トレーニング"),
          v("热身", "rè shēn", "ウォームアップ"),
          v("肌肉", "jī ròu", "筋肉"),
          v("酸痛", "suān tòng", "筋肉痛"),
          v("坚持", "jiān chí", "続ける"),
        ],
        dialogue: [
          { speaker: "A", text: "今天训练前先热身十分钟。", pinyin: "jīn tiān xùn liàn qián xiān rè shēn shí fēn zhōng", meaning: "今日はトレーニング前に10分ウォームアップする。" },
          { speaker: "B", text: "肌肉有点酸痛，但要坚持。", pinyin: "jī ròu yǒu diǎn suān tòng, dàn yào jiān chí", meaning: "筋肉が少し痛いけど、続けよう。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "赛事讨论",
        description: "讨论战术、选手与赛事走势",
        objectives: ["分析比赛", "评价选手表现"],
        vocab: [
          v("战术", "zhàn shù", "戦術"),
          v("防守", "fáng shǒu", "守備"),
          v("进攻", "jìn gōng", "攻撃"),
          v("发挥", "fā huī", "発揮"),
          v("逆转", "nì zhuǎn", "逆転"),
        ],
        dialogue: [
          { speaker: "A", text: "下半场战术调整很关键。", pinyin: "xià bàn chǎng zhàn shù tiáo zhěng hěn guān jiàn", meaning: "後半の戦術調整が鍵だった。" },
          { speaker: "B", text: "他今天发挥出色，完成逆转。", pinyin: "tā jīn tiān fā huī chū sè, wán chéng nì zhuǎn", meaning: "今日は素晴らしい活躍で逆転した。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "运动精神表达",
        description: "探讨体育精神与人生态度",
        objectives: ["表达体育精神", "联系人生感悟"],
        vocab: [
          v("拼搏", "pīn bó", "全力を尽くす"),
          v("毅力", "yì lì", "意志力"),
          v("团队", "tuán duì", "チーム"),
          v("荣誉", "róng yù", "栄誉"),
          v("超越", "chāo yuè", "超越する"),
          v("信念", "xìn niàn", "信念"),
        ],
        dialogue: [
          { speaker: "A", text: "体育精神的核心是拼搏与信念。", pinyin: "tǐ yù jīng shén de hé xīn shì pīn bó yǔ xìn niàn", meaning: "スポーツ精神の核心は全力と信念だ。" },
          { speaker: "B", text: "团队荣誉比个人超越更重要。", pinyin: "tuán duì róng yù bǐ gè rén chāo yuè gèng zhòng yào", meaning: "チームの栄誉は個人の超越より大切だ。" },
          { speaker: "A", text: "坚持训练需要强大毅力。", pinyin: "jiān chí xùn liàn xū yào qiáng dà yì lì", meaning: "トレーニング継続には強い意志力が要る。" },
        ],
      },
    },
  },
  {
    slug: "tech",
    nameZh: "科技",
    nameJa: "テクノロジー",
    category: "career",
    icon: "💻",
    sortOrder: 7,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "手机应用",
        description: "谈论手机与常用应用",
        objectives: ["说出科技产品词汇", "描述基本用途"],
        vocab: [
          v("手机", "shǒu jī", "スマホ"),
          v("应用", "yìng yòng", "アプリ"),
          v("下载", "xià zài", "ダウンロード"),
          v("网络", "wǎng luò", "ネットワーク"),
        ],
        dialogue: [
          { speaker: "A", text: "这个应用很好用。", pinyin: "zhè ge yìng yòng hěn hǎo yòng", meaning: "このアプリはとても使いやすい。" },
          { speaker: "B", text: "请先连接网络再下载。", pinyin: "qǐng xiān lián jiē wǎng luò zài xià zài", meaning: "ネットに接続してからダウンロードしてください。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "互联网基础",
        description: "上网、搜索与信息获取",
        objectives: ["描述上网行为", "使用搜索相关表达"],
        vocab: [
          v("搜索", "sōu suǒ", "検索"),
          v("网页", "wǎng yè", "ウェブページ"),
          v("账号", "zhàng hào", "アカウント"),
          v("密码", "mì mǎ", "パスワード"),
          v("登录", "dēng lù", "ログイン"),
        ],
        dialogue: [
          { speaker: "A", text: "请在网页上搜索一下。", pinyin: "qǐng zài wǎng yè shàng sōu suǒ yī xià", meaning: "ウェブで検索してみてください。" },
          { speaker: "B", text: "用账号和密码登录。", pinyin: "yòng zhàng hào hé mì mǎ dēng lù", meaning: "アカウントとパスワードでログインする。" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "AI 话题",
        description: "讨论人工智能与日常应用",
        objectives: ["谈论 AI 用途", "表达观点态度"],
        vocab: [
          v("人工智能", "rén gōng zhì néng", "人工知能（AI）"),
          v("效率", "xiào lǜ", "効率"),
          v("自动化", "zì dòng huà", "自動化"),
          v("算法", "suàn fǎ", "アルゴリズム"),
          v("隐私", "yǐn sī", "プライバシー"),
        ],
        dialogue: [
          { speaker: "A", text: "人工智能提高了工作效率。", pinyin: "rén gōng zhì néng tí gāo le gōng zuò xiào lǜ", meaning: "AIは仕事の効率を上げた。" },
          { speaker: "B", text: "但也要注意隐私问题。", pinyin: "dàn yě yào zhù yì yǐn sī wèn tí", meaning: "ただしプライバシーにも注意が必要だ。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "产品介绍",
        description: "介绍科技产品功能与优势",
        objectives: ["说明产品功能", "突出核心卖点"],
        vocab: [
          v("功能", "gōng néng", "機能"),
          v("升级", "shēng jí", "アップグレード"),
          v("兼容", "jiān róng", "互換性"),
          v("用户体验", "yòng hù tǐ yàn", "ユーザー体験"),
          v("创新", "chuàng xīn", "イノベーション"),
        ],
        dialogue: [
          { speaker: "A", text: "这次升级优化了用户体验。", pinyin: "zhè cì shēng jí yōu huà le yòng hù tǐ yàn", meaning: "今回のアップグレードでUXが改善された。" },
          { speaker: "B", text: "新功能兼容旧设备，很有创新。", pinyin: "xīn gōng néng jiān róng jiù shè bèi, hěn yǒu chuàng xīn", meaning: "新機能は旧端末とも互換性があり、革新的だ。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "科技趋势讨论",
        description: "讨论科技发展趋势与影响",
        objectives: ["分析科技趋势", "讨论社会影响"],
        vocab: [
          v("数字化", "shù zì huà", "デジタル化"),
          v("云计算", "yún jì suàn", "クラウドコンピューティング"),
          v("生态", "shēng tài", "エコシステム"),
          v("颠覆", "diān fù", "破壊的イノベーション"),
          v("赋能", "fù néng", "力を与える"),
          v("门槛", "mén kǎn", "ハードル"),
        ],
        dialogue: [
          { speaker: "A", text: "云计算正在颠覆传统IT生态。", pinyin: "yún jì suàn zhèng zài diān fù chuán tǒng IT shēng tài", meaning: "クラウドが従来のITエコシステムを変えている。" },
          { speaker: "B", text: "数字化降低了创业门槛。", pinyin: "shù zì huà jiàng dī le chuàng yè mén kǎn", meaning: "デジタル化で起業のハードルが下がった。" },
          { speaker: "A", text: "AI 赋能各行各业。", pinyin: "AI fù néng gè háng gè yè", meaning: "AIはあらゆる業界に力を与えている。" },
        ],
      },
    },
  },
  {
    slug: "history",
    nameZh: "历史",
    nameJa: "歴史",
    category: "culture",
    icon: "📜",
    sortOrder: 8,
    lessons: {
      [ProficiencyLevel.BEGINNER]: {
        title: "历史人物",
        description: "认识基础历史人物词汇",
        objectives: ["说出人物相关词", "简单介绍人物"],
        vocab: [
          v("历史", "lì shǐ", "歴史"),
          v("人物", "rén wù", "人物"),
          v("古代", "gǔ dài", "古代"),
          v("著名", "zhù míng", "有名な"),
        ],
        dialogue: [
          { speaker: "A", text: "这是一位著名的历史人物。", pinyin: "zhè shì yī wèi zhù míng de lì shǐ rén wù", meaning: "これは有名な歴史上の人物です。" },
          { speaker: "B", text: "他生活在古代。", pinyin: "tā shēng huó zài gǔ dài", meaning: "彼は古代に生きていた。" },
        ],
      },
      [ProficiencyLevel.ELEMENTARY]: {
        title: "历史事件",
        description: "描述历史事件的基本表达",
        objectives: ["说出事件词汇", "描述发生了什么"],
        vocab: [
          v("事件", "shì jiàn", "事件"),
          v("战争", "zhàn zhēng", "戦争"),
          v("和平", "hé píng", "平和"),
          v("发生", "fā shēng", "起こる"),
          v("影响", "yǐng xiǎng", "影響"),
        ],
        dialogue: [
          { speaker: "A", text: "这场战争影响了很多人。", pinyin: "zhè chǎng zhàn zhēng yǐng xiǎng le hěn duō rén", meaning: "この戦争は多くの人に影響を与えた。" },
          { speaker: "B", text: "后来终于恢复了和平。", pinyin: "hòu lái zhōng yú huī fù le hé píng", meaning: "その後ついに平和が戻った。" },
        ],
      },
      [ProficiencyLevel.INTERMEDIATE]: {
        title: "年代表达",
        description: "用年份描述历史事件顺序",
        objectives: ["说出年份", "描述时间顺序"],
        vocab: [
          v("世纪", "shì jì", "世紀"),
          v("朝代", "cháo dài", "王朝"),
          v("建立", "jiàn lì", "建国・設立"),
          v("灭亡", "miè wáng", "滅亡"),
          v("考古", "kǎo gǔ", "考古学"),
        ],
        dialogue: [
          { speaker: "A", text: "这个朝代建立于十三世纪。", pinyin: "zhè ge cháo dài jiàn lì yú shí sān shì jì", meaning: "この王朝は13世紀に成立した。" },
          { speaker: "B", text: "考古发现帮助我们了解历史。", pinyin: "kǎo gǔ fā xiàn bāng zhù wǒ men liǎo jiě lì shǐ", meaning: "考古の発見が歴史理解を助ける。" },
        ],
      },
      [ProficiencyLevel.UPPER_INTERMEDIATE]: {
        title: "朝代文化",
        description: "介绍朝代文化与历史遗产",
        objectives: ["介绍文化特点", "描述历史遗产"],
        vocab: [
          v("遗产", "yí chǎn", "遺産"),
          v("文明", "wén míng", "文明"),
          v("制度", "zhì dù", "制度"),
          v("交流", "jiāo liú", "交流"),
          v("繁荣", "fán róng", "繁栄"),
        ],
        dialogue: [
          { speaker: "A", text: "唐朝是文化交流繁荣的时代。", pinyin: "táng cháo shì wén huà jiāo liú fán róng de shí dài", meaning: "唐王朝は文化交流が繁栄した時代だ。" },
          { speaker: "B", text: "许多制度影响至今。", pinyin: "xǔ duō zhì dù yǐng xiǎng zhì jīn", meaning: "多くの制度が今も影響している。" },
        ],
      },
      [ProficiencyLevel.ADVANCED]: {
        title: "历史观点讨论",
        description: "讨论历史评价与多元视角",
        objectives: ["表达历史观点", "讨论因果与评价"],
        vocab: [
          v("视角", "shì jiǎo", "視点"),
          v("因果", "yīn guǒ", "因果"),
          v("史料", "shǐ liào", "史料"),
          v("辩证", "biàn zhèng", "弁証的"),
          v("传承", "chuán chéng", "継承"),
          v("反思", "fǎn sī", "反省"),
        ],
        dialogue: [
          { speaker: "A", text: "历史需要从多角度辩证地看。", pinyin: "lì shǐ xū yào cóng duō jiǎo dù biàn zhèng de kàn", meaning: "歴史は多角的・弁証的に見る必要がある。" },
          { speaker: "B", text: "史料不足时更要谨慎反思。", pinyin: "shǐ liào bù zú shí gèng yào jǐn shèn fǎn sī", meaning: "史料が不足するときほど慎重に反省すべきだ。" },
          { speaker: "A", text: "文明的传承离不开对因果的理解。", pinyin: "wén míng de chuán chéng lí bù kāi duì yīn guǒ de lǐ jiě", meaning: "文明の継承は因果の理解なくして成り立たない。" },
        ],
      },
    },
  },
];
